import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import LoaderLinear from "./components/loader";
import Login from "./components/login";
import BgContainer from "./components/containers/bgContainer";
import Header from "./components/header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" >
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-custom-white dark:bg-bg-dark`}
      >
        <div className="">
          <div className="static">
            <div className="absolute w-96 h-96 bg-primary-dark rounded-full opacity-25 -top-28 -left-32 z-[0] backdrop-blur-sm"></div>
          </div>
          <BgContainer>
            {children}
          </BgContainer >
          <div>
            <div className="static">
              <div className="absolute bottom-0 z-10 left-0 w-full max-h-[350px] overflow-hidden">
                <div>
                  <svg xmlnsXlink="http://www.w3.org/1999/xlink" id="wave" style={{ transform: "rotate(0deg)", transition: "0.3s" }} viewBox="0 0 1440 240" version="1.1" xmlns="http://www.w3.org/2000/svg"><defs><linearGradient id="sw-gradient-0" x1="0" x2="0" y1="1" y2="0"><stop stopColor="rgba(14, 190, 127, 1)" offset="0%" /><stop stopColor="rgba(106.26, 157.418, 138.815, 1)" offset="100%" /></linearGradient></defs><path style={{ transform: "translate(0, 0px)", opacity: "1" }} fill="url(#sw-gradient-0)" d="M0,24L30,44C60,64,120,104,180,116C240,128,300,112,360,124C420,136,480,176,540,168C600,160,660,104,720,100C780,96,840,144,900,172C960,200,1020,208,1080,196C1140,184,1200,152,1260,120C1320,88,1380,56,1440,52C1500,48,1560,72,1620,100C1680,128,1740,160,1800,144C1860,128,1920,64,1980,36C2040,8,2100,16,2160,28C2220,40,2280,56,2340,68C2400,80,2460,88,2520,96C2580,104,2640,112,2700,120C2760,128,2820,136,2880,120C2940,104,3000,64,3060,52C3120,40,3180,56,3240,72C3300,88,3360,104,3420,128C3480,152,3540,184,3600,192C3660,200,3720,184,3780,168C3840,152,3900,136,3960,124C4020,112,4080,104,4140,104C4200,104,4260,112,4290,116L4320,120L4320,240L4290,240C4260,240,4200,240,4140,240C4080,240,4020,240,3960,240C3900,240,3840,240,3780,240C3720,240,3660,240,3600,240C3540,240,3480,240,3420,240C3360,240,3300,240,3240,240C3180,240,3120,240,3060,240C3000,240,2940,240,2880,240C2820,240,2760,240,2700,240C2640,240,2580,240,2520,240C2460,240,2400,240,2340,240C2280,240,2220,240,2160,240C2100,240,2040,240,1980,240C1920,240,1860,240,1800,240C1740,240,1680,240,1620,240C1560,240,1500,240,1440,240C1380,240,1320,240,1260,240C1200,240,1140,240,1080,240C1020,240,960,240,900,240C840,240,780,240,720,240C660,240,600,240,540,240C480,240,420,240,360,240C300,240,240,240,180,240C120,240,60,240,30,240L0,240Z" /><defs><linearGradient id="sw-gradient-1" x1="0" x2="0" y1="1" y2="0"><stop stopColor="rgba(14, 190, 127, 1)" offset="0%" /><stop stopColor="rgba(57.906, 107.329, 89.357, 1)" offset="100%" /></linearGradient></defs><path style={{ transform: "translate(0, 50px)", opacity: "0.9" }} fill="url(#sw-gradient-1)" d="M0,216L30,188C60,160,120,104,180,80C240,56,300,64,360,76C420,88,480,104,540,116C600,128,660,136,720,116C780,96,840,48,900,56C960,64,1020,128,1080,148C1140,168,1200,144,1260,120C1320,96,1380,72,1440,68C1500,64,1560,80,1620,76C1680,72,1740,48,1800,60C1860,72,1920,120,1980,132C2040,144,2100,120,2160,104C2220,88,2280,80,2340,72C2400,64,2460,56,2520,52C2580,48,2640,48,2700,44C2760,40,2820,32,2880,60C2940,88,3000,152,3060,160C3120,168,3180,120,3240,100C3300,80,3360,88,3420,88C3480,88,3540,80,3600,72C3660,64,3720,56,3780,48C3840,40,3900,32,3960,32C4020,32,4080,40,4140,60C4200,80,4260,112,4290,128L4320,144L4320,240L4290,240C4260,240,4200,240,4140,240C4080,240,4020,240,3960,240C3900,240,3840,240,3780,240C3720,240,3660,240,3600,240C3540,240,3480,240,3420,240C3360,240,3300,240,3240,240C3180,240,3120,240,3060,240C3000,240,2940,240,2880,240C2820,240,2760,240,2700,240C2640,240,2580,240,2520,240C2460,240,2400,240,2340,240C2280,240,2220,240,2160,240C2100,240,2040,240,1980,240C1920,240,1860,240,1800,240C1740,240,1680,240,1620,240C1560,240,1500,240,1440,240C1380,240,1320,240,1260,240C1200,240,1140,240,1080,240C1020,240,960,240,900,240C840,240,780,240,720,240C660,240,600,240,540,240C480,240,420,240,360,240C300,240,240,240,180,240C120,240,60,240,30,240L0,240Z" /></svg>
                </div>
              </div>
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
